---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: python-standard-{{ .Values.appName }}
  namespace: {{ .Values.namespace }}
spec:
  params:
    - default: {{ .Values.appName }}
      name: APP_NAME
      type: string
    - default: 'https://github.com/redhat-mal/python-hello-world.git'
      name: GIT_REPO
      type: string
    - name: GIT_CONTEXT_DIR
      type: string
      default: src
    - default: main
      name: GIT_REVISION
      type: string
    - default: >-
        image-registry.openshift-image-registry.svc:5000/{{ .Values.namespace }}/{{ .Values.appName }}
      name: IMAGE_NAME
      type: string
  tasks:
    - name: fetch-repository
      params:
        - name: url
          value: $(params.GIT_REPO)
        - name: revision
          value: $(params.GIT_REVISION)
        - name: deleteExisting
          value: 'true'
        - name: subdirectory
          value: ''
      taskRef:
        kind: ClusterTask
        name: git-clone
      workspaces:
        - name: output
          workspace: workspace
    #- name: debug
    #  runAfter:
    #  - fetch-repository
    #  taskRef:
    #    kind: Task
    #    name: debug-files
    #  workspaces:
    #    - name: source
    #      workspace: workspace  
{{- if eq .Values.builderType "python" }}
    - name: build
      params:
        - name: IMAGE
          value: $(params.IMAGE_NAME)
        - name: TLSVERIFY
          value: 'false'
        - name: PATH_CONTEXT
          value: $(params.GIT_CONTEXT_DIR)
      runAfter:
        - debug
      taskRef:
        kind: ClusterTask
        name: s2i-python-3
      workspaces:
        - name: source
          workspace: workspace
{{- end }}
{{- if eq .Values.builderType "buildah" }}
    - name: build
      params:
        - name: IMAGE
          value: $(params.IMAGE_NAME)
{{- if .Values.buildah.builderImage }}
        - name: BUILDER_IMAGE
          value: '{{ .Values.buildah.builderImage }}'
{{- end }}
        - name: CONTEXT
          value: $(params.GIT_CONTEXT_DIR)
        - name: TLSVERIFY
          value: 'false'
      runAfter:
        - fetch-repository
      taskRef:
        kind: ClusterTask
        name: buildah
      workspaces:
        - name: source
          workspace: workspace
{{- end }}
{{- if eq .Values.builderType "java11" }}
    - name: build
      params:
        - name: IMAGE
          value: $(params.IMAGE_NAME)
        - name: TLSVERIFY
          value: 'false'
        - name: PATH_CONTEXT
          value: $(params.GIT_CONTEXT_DIR)
      runAfter:
        - fetch-repository
      taskRef:
        kind: ClusterTask
        name: s2i-java-11
      workspaces:
        - name: source
          workspace: workspace
{{- end }}
    - name: kn-deploy
      params:
        - name: ARGS
          value:
            - service 
            - create
            - $(params.APP_NAME)
            - --force
            - "--image=$(params.IMAGE_NAME)"
      runAfter:
        - build
      taskRef:
        kind: ClusterTask
        name: kn
  workspaces:
    - name: workspace
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
  name: debug-files
  namespace: {{ .Values.namespace }}
spec:
  workspaces:
  - name: source
  params:
    - name: imageTag
      description: The image tag
      default: '*'
  steps:
  - name: git-debug1
    image: quay.io/openshift-pipeline/openshift-cli:latest
    workingDir: /workspace/source
    command: ["/bin/bash"]
    args:
      - '-c'
      - ls -lrtR .



